#!/bin/bash
# Bootstrap script used to run setup tasks for Misago admin image

# Text styles
RED='\033[0;31m'
BOLD=$(tput bold)
NORMAL=$(tput sgr0)

# Utility functions used by action commands
error() {
    echo -e "${RED}Error:${NORMAL} $1"
}

# Commands
install_plugins() {
    if [[ -d plugins ]]; then
        # Run setup script for plugins JS
        node setupPlugins.js
    fi
}

prepare_deploy() {
    npm run build
    mv build/asset-manifest.json build/static/admin/asset-manifest.json
    mkdir build_tmp
    mv build/static/admin build_tmp/admin
    rm -rf build
    mv build_tmp build
}

# Command dispatcher
if [[ $1 ]]; then
    if [[ $1 = "start" ]]; then
        install_plugins
        npm run compilemessages
        npm run start
    elif [[ $1 = "plugins" ]]; then
        install_plugins
    elif [[ $1 = "deploy" ]]; then
        install_plugins
        npm run compilemessages
        prepare_deploy
    else
        invalid_argument $1
        echo -e "Invalid argument: ${RED}$1${NORMAL}"
        exit 1
    fi
else
    error "This command needs to be ran with an argument."
    exit 1
fi
